# Generated by Django 5.0.7 on 2024-08-05 00:38

# 통합된 마이그레이션 파일 (0001_initial.py)
import datetime
import django.utils.timezone
import mandalarts.models
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_title', models.CharField(max_length=18)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badge')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BadgeUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unlock_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandalarts.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(blank=True, default='', max_length=18, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('final_goal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mandalarts.Mandalart')),
            ],
        ),
        migrations.CreateModel(
            name='GoalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_date', models.DateField(auto_now_add=True)),
                ('feedback', models.CharField(blank=True, max_length=18, null=True)),
                ('achieved_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandalarts.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mandalarts.UserBadge')),
            ],
        ),
        migrations.CreateModel(
            name='Mandalart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='', max_length=18)),
                ('man_title', models.CharField(default='', max_length=18, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('unlockable_badge_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgoal_title', models.CharField(blank=True, default='', max_length=18, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mandalarts.models.mandalart_directory_path)),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mandalarts.Goal')),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandalarts.Badge')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mandalarts.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='goalachievement',
            unique_together={('user', 'achieved_goal')},
        ),
    ]
