# Generated by Django 4.2.14 on 2024-07-30 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=18)),
                ('image', models.ImageField(blank=True, null=True, upload_to='badge')),
                ('unlocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=18, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=18, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mandalart/')),
                ('completed', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mandalarts.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('unlockable_badge_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mandalart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default='', max_length=18, unique=True)),
                ('title', models.CharField(default='', max_length=18, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='final_goal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mandalarts.mandalart'),
        ),
        migrations.CreateModel(
            name='BadgeUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlock_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandalarts.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_date', models.DateField(auto_now_add=True)),
                ('feedback', models.CharField(blank=True, max_length=18, null=True)),
                ('achieved_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandalarts.goal')),
                ('goal_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mandalarts.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achieved_goal')},
            },
        ),
    ]
