# Generated by Django 4.2.14 on 2024-08-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mandalarts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_date', models.DateField(auto_now_add=True)),
                ('feedback', models.CharField(blank=True, max_length=18, null=True)),
                ('achieved_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandalarts.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mandalarts.userbadge')),
            ],
            options={
                'unique_together': {('user', 'achieved_goal')},
            },
        ),
    ]
