# Generated by Django 5.0.7 on 2024-08-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goalachievement',
            unique_together=set(),
        ),
    ]
