# Generated by Django 4.2.14 on 2024-08-01 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0003_remove_badge_unlocked_badge_created_at_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='goal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='mandalarts.goal'),
        ),
    ]
