# Generated by Django 4.2.14 on 2024-08-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0004_notification_created_at_userbadge_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mandalarts.goal'),
        ),
    ]
