# Generated by Django 4.2.14 on 2024-08-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0002_alter_goalachievement_unique_together'),
        ('mandalarts', '0005_alter_userbadge_goal'),
    ]

    operations = [
    ]
