# Generated by Django 4.2.14 on 2024-08-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0005_alter_userbadge_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailybadge',
            old_name='badge_title',
            new_name='badge',
        ),
    ]
