# Generated by Django 4.2.14 on 2024-08-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0006_rename_badge_title_dailybadge_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalachievement',
            old_name='goal_badge',
            new_name='badge',
        ),
        migrations.AlterUniqueTogether(
            name='goalachievement',
            unique_together=set(),
        ),
    ]
