# Generated by Django 4.2.14 on 2024-08-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0007_rename_goal_badge_goalachievement_badge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalachievement',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='mandalarts.userbadge'),
        ),
    ]
