# Generated by Django 5.0.7 on 2024-08-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0002_alter_goalachievement_unique_together'),
        ('mandalarts', '0008_alter_goalachievement_badge'),
    ]

    operations = [
    ]
