# Generated by Django 4.2.14 on 2024-08-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0010_alter_subgoal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='title',
            new_name='badge_title',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='title',
            new_name='goal_title',
        ),
        migrations.RenameField(
            model_name='mandalart',
            old_name='title',
            new_name='man_title',
        ),
        migrations.RenameField(
            model_name='subgoal',
            old_name='title',
            new_name='subgoal_title',
        ),
    ]
