# Generated by Django 4.2.14 on 2024-08-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0011_rename_title_badge_badge_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailybadge',
            old_name='badge',
            new_name='user_badge',
        ),
        migrations.RenameField(
            model_name='goalachievement',
            old_name='badge',
            new_name='user_badge',
        ),
    ]
