# Generated by Django 4.2.14 on 2024-08-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0013_remove_dailybadge_user_badge_dailybadge_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandalart',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailybadge',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandalarts.badge'),
        ),
    ]
