# Generated by Django 4.2.14 on 2024-08-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandalarts', '0014_mandalart_is_selected_alter_dailybadge_badge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyBadge',
        ),
    ]
