# Generated by Django 5.0.7 on 2024-08-05 17:19

import diarys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='diary',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=diarys.models.diary_directory_path),
        ),
    ]
