# Generated by Django 5.0.7 on 2024-08-01 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarys', '0003_alter_diary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='updated_at',
        ),
    ]
